apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: odoo-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.odoo.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
